<?php

namespace AppBundle\Repository;

/**
 * SupplierContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupplierContactRepository extends \Doctrine\ORM\EntityRepository
{
}
